### ISSUE TITLE
[bug]: debian-base:trixie image - sudo: unable to initialize PAM: Critical error - immediate abort

### ISSUE THREAD

**Issue by Domini** [docker-hardened-images/catalog#67]
### Docker Hardened Image

debian-base:trixie

### Bug Description

When building images it's a good practice to gatekeep few necessary admin commands via sudo and run container under nonroot.

It works in official debian:trixie-slim image, but does not work in dhi.io/debian-base:trixie.

### Steps to Reproduce

```
$ docker run --interactive --tty dhi.io/debian-base:trixie
root@7e87f5a25425:/# apt-get update && apt-get install -y sudo
Get:1 http://deb.debian.org/debian trixie InRelease [140 kB]
Get:2 http://deb.debian.org/debian trixie-updates InRelease [47.3 kB]
Get:3 http://deb.debian.org/debian-security trixie-security InRelease [43.4 kB]
Get:4 http://deb.debian.org/debian trixie/main Sources [10.5 MB]
Get:5 http://deb.debian.org/debian trixie/main arm64 Packages [9607 kB]
Get:6 http://deb.debian.org/debian trixie-updates/main Sources [2788 B]
Get:7 http://deb.debian.org/debian trixie-updates/main arm64 Packages [5404 B]
Get:8 http://deb.debian.org/debian-security trixie-security/main Sources [116 kB]
Get:9 http://deb.debian.org/debian-security trixie-security/main arm64 Packages [93.9 kB]
Fetched 20.6 MB in 2s (9995 kB/s)                         
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
The following additional packages will be installed:
  init-system-helpers libapparmor1
The following NEW packages will be installed:
  init-system-helpers libapparmor1 sudo
0 upgraded, 3 newly installed, 0 to remove and 6 not upgraded.
Need to get 2074 kB of archives.
After this operation, 7534 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian trixie/main arm64 init-system-helpers all 1.69~deb13u1 [39.4 kB]
Get:2 http://deb.debian.org/debian trixie/main arm64 libapparmor1 arm64 4.1.0-1 [42.9 kB]
Get:3 http://deb.debian.org/debian trixie/main arm64 sudo arm64 1.9.16p2-3 [1992 kB]
Fetched 2074 kB in 0s (54.8 MB/s)
Selecting previously unselected package init-system-helpers.
(Reading database ... 6648 files and directories currently installed.)
Preparing to unpack .../init-system-helpers_1.69~deb13u1_all.deb ...
Unpacking init-system-helpers (1.69~deb13u1) ...
Setting up init-system-helpers (1.69~deb13u1) ...
Selecting previously unselected package libapparmor1:arm64.
(Reading database ... 6691 files and directories currently installed.)
Preparing to unpack .../libapparmor1_4.1.0-1_arm64.deb ...
Unpacking libapparmor1:arm64 (4.1.0-1) ...
Selecting previously unselected package sudo.
Preparing to unpack .../sudo_1.9.16p2-3_arm64.deb ...
Unpacking sudo (1.9.16p2-3) ...
Setting up libapparmor1:arm64 (4.1.0-1) ...
Setting up sudo (1.9.16p2-3) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: WARNING: No init system and policy-rc.d missing! Defaulting to block.
root@7e87f5a25425:/# sudo cat
...
root@7e87f5a25425:/# su 
...
root@7e87f5a25425:/# 
```

### Expected Behavior

No errors.

### Actual Behavior

```
root@7e87f5a25425:/# sudo cat
sudo: unable to initialize PAM: Critical error - immediate abort
root@7e87f5a25425:/# su 
su: Critical error - immediate abort
```

### Environment

-

### Relevant Logs

```shell

```

### Additional Context

Same behaviour from `nonroot` if you create a Dockerfile with
```
FROM dhi.io/debian-base:trixie
USER nonroot
```

### Pre-submission Checklist

- [x] I have searched existing issues to ensure this bug hasn't been reported before
- [x] I have provided all the requested information above
- [x] I have tested this with the latest available version of the hardened image

**Comment by cdupuis** [comment]
@Domini, thanks for filing this.

Could you try the following in your `Dockerfile`:

```Dockerfile
RUN  apt-get update && \
    apt-get install -y libpam-runtime libpam-modules sudo && \
    pam-auth-update --package --force && \
    rm -rf /var/lib/apt/lists/*
```

This should fix this, 

cd

**Comment by cdupuis** [comment]
Let's leave it open. Not sure what to do yet.

**Comment by Domini** [comment]
The issue from the initial post is still reproducible in the latest dhi.io/debian-base:trixie-dev without manually calling `pam-auth-update --package --force`

@cdupuis, just to double-check, is this intentional? in the end you decided not to enclose the neccessary information at compile time and rather call `pam-auth-update --package --force` in runtime?

**Comment by thorfi** [comment]
Bump this is still broken
